apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace }}
  name: ti-install-sa

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: ti-install-admin
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["create", "get", "patch", "update", "list", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create", "get", "patch", "update", "list", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get", "patch", "update", "list", "delete"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get","delete"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["create", "get", "patch", "update", "list", "delete"]
- apiGroups: ["trusted.identity"] # "" indicates the core API group
  resources: ["clustertis"]
  verbs: ["get", "update", "list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ti-admin-install-bind
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: ti-install-sa
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: ti-install-admin
  apiGroup: rbac.authorization.k8s.io
---

# ClusterRole is needed to execute operations on MutatingWebhookConfiguration
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: mutwebhookr-mgr
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["create", "get", "patch", "update", "list", "delete"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ti-cluster-role-bind
  namespace: ""
subjects:
- kind: ServiceAccount
  name: ti-install-sa
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: mutwebhookr-mgr
  apiGroup: rbac.authorization.k8s.io
