# Default values for ti-key-relase-1
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# target namespace for the deployment
namespace: trusted-identity

# version of ti-components
tiVersion: v0.8

# Cluster Information
cluster:
  name: cluster-name
  region: dal01

# Section related to JWT token creation
jwt:
  # expireSec - Time To Live for JWT token (in seconds)
  expireSec: 30
  issuer: wsched@us.ibm.com

# vtpmService - vTPM Service is accessable only from within the namespace
vtpmService:
  name: vtpm-service
  port: 8012


# Values below are used to create a secret: `ti-keys-config`
# vault-address e.g. https://1.1.1.1:32222
vaultAddress: https://169.62.157.164:32654


# Not recommended for user to configure this. Hyperkube image to use when executing
# kubectl commands
hyperkube:
  repository: quay.io/coreos/hyperkube
  tag: v1.7.6_coreos.0
