# Default values for ti-key-relase-1
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# target namespace for the deployment
namespace: trusted-identity

# version of ti-components
tiVersion: v0.18

# Cluster Information
cluster:
  name: cluster-name
  region: dal01

# Section related to JWT token creation
jwt:
  # expireSec - Time To Live for JWT token (in seconds)
  expireSec: 30
  issuer: wsched@us.ibm.com

# jssService - main vTPM Service is accessable only from within the namespace
jssService:
  name: jss-service
  port: 8012
  # jssSerivce.type: this is the name of the image used for building JSS server
  # available options are:
  #   - jss-server - standard JSS server (deafult)
  #   - vtpm-server - vTPM v1
  #   - vtpm2-server - vTPM v2
  type: jss-server

# ingress - some JSS calls are publicly available via ingress
ingress:
  enabled: true
  path: /
  # host: specify here the access to the ingress
  # for IKS: `ibmcloud ks cluster-get <cluster-name> | grep Ingress`
  # for ICP: set ingress enabled to false, keep the host empty and use IPs directly (typically master or proxy IP)
  host:
  #  - mycluster.eu-de.containers.appdomain.cloud

# createVaultCert - if true, unique certs will be created
# during Init Containers and inserted to Vault
createVaultCert: false

# Values below are used to create a secret: `ti-keys-config`
# vault-address e.g. https://1.1.1.1:32222
vaultAddress: https://169.62.157.164:32654


# Not recommended for user to configure this. Hyperkube image to use when executing
# kubectl commands
hyperkube:
  repository: gcr.io/google_containers/hyperkube
  tag: v1.14.3
