apiVersion: v1
appVersion: "1.0"
description: A Helm chart for setting up TSI nodes
name: tsi-node-setup
home: https://github.com/IBM/trusted-service-identity
# version: // version and appVersion are dynamically set by the buildTSI.sh script
# appVersion:
maintainers:
  - name: Brandon Lum
    email: Brandon.Lum@ibm.com
  - name: Mariusz Sabath
    email: sabath@us.ibm.com
