apiVersion: v1
data:
{{- if .Files.Glob "keys/*"  }}
  address: {{ .Values.vaultAddress | b64enc }}
  root-token: {{ .Values.rootToken | b64enc }}
  rootCA.crt: {{ .Values.rootCaCrt | b64enc }}
  rootCA.key: {{ .Values.rootCaKey | b64enc }}
  rootCA.srl: {{ .Values.rootCaSrl | b64enc }}
{{ (.Files.Glob "keys/*").AsSecrets | indent 2 }}
kind: Secret
metadata:
  name: ti-keys-config
  namespace: {{ .Values.namespace }}
type: Opaque
{{- else }}
ERROR: Missing keys directory (keys/)
{{- end }}
