apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace }}
  name: ti-admin-sa

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: ti-setup-admin
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["create", "get", "patch", "update", "list", "delete"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["daemonsets"]
  verbs: ["get", "patch", "update", "list", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create", "get", "patch", "update", "list", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ti-setup-admin-bind
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: ti-admin-sa
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: ti-setup-admin
  apiGroup: rbac.authorization.k8s.io
