apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: vault-cli
  name: vault-cli
  namespace: trusted-identity
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        admission.trusted.identity/inject: "true"
        tsi.secrets: |
             - tsi.secret/name: "dummy"
               tsi.secret/role: "demo"
               tsi.secret/vault-path: "secret/ti-demo-all"
               tsi.secret/local-name: "mysecrets/secret-test1"
             - tsi.secret/name: "invalid"
               tsi.secret/role: "demo"
               tsi.secret/vault-path: "secret/ti-demo-all"
               tsi.secret/local-name: "mysecrets/secret-invalid"
             - tsi.secret/name: "non-existing"
               tsi.secret/role: "demo"
               tsi.secret/vault-path: "secret/nothing"
               tsi.secret/local-name: "mysecrets/non-existing"
      labels:
        app: vault-cli
      name: vault-cli
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: vault-cli
          image: res-kompass-kompass-docker-local.artifactory.swg-devops.com/vault-cli:v0.3
          imagePullPolicy: Always
