apiVersion: v1
kind: ConfigMap
metadata:
  name: ti-jwt-configmap
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "ti-key-release.name" . }}
    chart: {{ template "ti-key-release.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  execute-get-key.sh: |-
    while true; do python /gen-jwt.py /secret/jwt/key.pem --expire=30 --claims=$(cat /jwt/claims) > /usr/share/jwt/token;sleep 25; done
