apiVersion: v1
kind: ConfigMap
metadata:
  name: ti-jwt-configmap
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "ti-key-release.name" . }}
    chart: {{ template "ti-key-release.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  execute-get-key.sh: |-
    while true
     do
      echo -n '' > /tmp/claims
      echo -n "pod=$(cat /pod-metadata/ti-pod-name)&" >> /tmp/claims
      echo -n "namespace=$(cat /pod-metadata/ti-pod-namespace)&" >> /tmp/claims
      echo -n "images=$(cat /pod-metadata/ti-images | sha256sum | awk '{print $1}')&" >> /tmp/claims
      echo -n "cluster-name=$(cat /pod-metadata/ti-cluster-name)&" >> /tmp/claims
      echo -n "cluster-region=$(cat /pod-metadata/ti-cluster-region)&" >> /tmp/claims
      echo -n "machineid=$(cat /host/etc/machine-id)" >> /tmp/claims
      curl http://{{ .Values.vtpmService.name }}:{{ .Values.vtpmService.port }}/getJWT?"$(cat /tmp/claims)" > /usr/share/jwt/token
      sleep $(({{ int .Values.jwt.expireSec }} - 5))
    done
