{{ define "mutatingwebhook.tpl" }}
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: tsi-mutate-webhook-cfg
  labels:
    app: tsi-mutate
webhooks:
  - name: tsi-mutate.trusted-service-identity.ibm
    clientConfig:
      service:
        name: tsi-mutate-webhook-svc
        namespace: {{ .Values.namespace }}
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "*"
{{ end }}
