apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-injector-webhook-configmap
data:
  initcontainerconfig.yaml: |
      initContainers:
      - name: gen-vault-cert
        image: lumjjb/gen-vault-cert:v1
        imagePullPolicy: Always
        volumeMounts:
          - name: pod-metadata
            mountPath: /pod-metadata
      volumes:
        - name: pod-metadata
          downwardAPI:
            items:
              - path: "ti-secret"
                fieldRef:
                  fieldPath: metadata.annotations['admission.trusted.identity/ti-secret-key']
        - name: ti-vault-secret
          secret:
            secretName: ti-vault-
      addVolumeMounts:
        - name: ti-vault-secret
          mountPath: /vault-certs
          readOnly: true
