apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ti-revoker-deployment
  labels:
    app: ti-revoker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ti-revoker
    spec:
      serviceAccountName: ti-sa
      containers:
        - name: ti-revoker
          image: lumjjb/ti-revoker:v1
          imagePullPolicy: Always
          args:
            - -namespace=trusted-identity
            - -alsologtostderr
            - -v=4
            - 2>&1
