apiVersion: v1
kind: ServiceAccount
metadata:
  name: ti-sa
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: trusted-identity
  name: ti-admin
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "update", "list", "delete"]
- apiGroups: ["trusted.identity"] # "" indicates the core API group
  resources: ["clusterti"]
  verbs: ["get", "update", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ti-admin-bind
subjects:
- kind: ServiceAccount
  name: ti-sa
  namespace: trusted-identity
roleRef:
  kind: ClusterRole
  name: ti-admin
  apiGroup: rbac.authorization.k8s.io
