apiVersion: batch/v1
kind: Job
metadata:
  name: delete-install-sa
  namespace: {{ index .Values "ti-key-release-1" "namespace" }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "10"
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app: {{ template "ti-key-release.name" . }}
    chart: {{ template "ti-key-release.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      name: delete-install-sa
      labels:
        app: {{ template "ti-key-release.name" . }}
        chart: {{ template "ti-key-release.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      serviceAccountName: ti-install-sa
      containers:
        - name: hyperkube
          image: "{{ .Values.hyperkube.repository }}:{{ .Values.hyperkube.tag }}"
          command:
            - /kubectl
            - delete
            - sa
            - ti-install-sa
            - -n
            - {{ index .Values "ti-key-release-1" "namespace" }}
      restartPolicy: OnFailure
