{{- if index .Values "ti-key-release-1" "ingress" "enabled" -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jss-ingress
  namespace: {{ index .Values "ti-key-release-1" "namespace" }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: {{ .Values.ingress.path }}
          backend:
            serviceName: {{ index .Values "ti-key-release-1" "jssService" "name" }}
            servicePort: {{ index .Values "ti-key-release-1" "jssService" "port" }}
{{- end }}
