apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: {{ index .Values "ti-key-release-1" "namespace" }}
  name: jss-server
spec:
  selector:
    matchLabels:
      name: jss-server
  template:
    metadata:
      labels:
        name: jss-server
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: jss-server
          image: res-kompass-kompass-docker-local.artifactory.swg-devops.com/{{ index .Values "ti-key-release-1" "jssService" "type" }}:{{ .Values.tiVersion }}
          imagePullPolicy: Always
          env:
            - name: ISS
              # this doublequotes actually works :)
              value: "{{ index .Values "ti-key-release-1" "jwt" "issuer" }}"
            - name: TTL_SEC
              value: "{{ index .Values "ti-key-release-1" "jwt" "expireSec" }}"
          ports:
          - name: http
            containerPort: 5000
            protocol: TCP
            hostPort: 5000
          volumeMounts:
          - mountPath: /host/tsi-secure
            name: ti-volume
          - mountPath: /logs
            name: host-logs
      volumes:
      - name: ti-volume
        hostPath:
          # directory location on host
           path: /ti-secret
           # directory might not exist
           type: DirectoryOrCreate
      - name: host-logs
        hostPath:
          # directory location on host
           path: /var/log
           type: Directory
