apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ index .Values "ti-key-release-1" "namespace" }}
  name: jss-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jss-server
        version: v1
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: jss-server
          image: res-kompass-kompass-docker-local.artifactory.swg-devops.com/{{ index .Values "ti-key-release-1" "jssService" "type" }}:{{ .Values.tiVersion }}
          imagePullPolicy: Always
          env:
            - name: ISS
              # this doublequotes actually works :)
              value: "{{ index .Values "ti-key-release-1" "jwt" "issuer" }}"
            - name: TTL_SEC
              value: "{{ index .Values "ti-key-release-1" "jwt" "expireSec" }}"
          ports:
          - name: http
            containerPort: 5000
            protocol: TCP
