{{- if index .Values "ti-key-release-1" "createVaultCert" }}

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ index .Values "ti-key-release-1" "namespace" }}
  name: ti-revoker-deployment
  labels:
    app: ti-revoker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ti-revoker
    spec:
      serviceAccountName: ti-sa
      volumes:
      - name: ti-skeys
        secret:
          secretName: ti-keys-config
      - name: ti-keys
        hostPath:
          path: /ti/secrets/keys
          type: Directory
      containers:
        - name: ti-revoker
          image: {{ .Values.tiRepo }}/ti-revoker:{{ .Values.tiVersion }}
          imagePullPolicy: Always
          args:
            - -namespace=trusted-identity
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
          - name: ti-keys
            mountPath: /keys
            readOnly: true
          - name: ti-skeys
            mountPath: /skeys
            readOnly: true
{{- end }}
