apiVersion: v1
kind: Service
metadata:
  namespace: {{ index .Values "ti-key-release-1" "namespace" }}
  name: ti-injector-webhook-svc
  labels:
    app: ti-injector
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: ti-injector
