kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: mutwebhookr-mgr
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["create", "get", "patch", "update", "list", "delete"]

---

# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-secrets-global
  namespace: ""
subjects:
- kind: ServiceAccount
  name: ti-sa
  namespace: trusted-identity
roleRef:
  kind: ClusterRole
  name: mutwebhookr-mgr 
  apiGroup: rbac.authorization.k8s.io
