apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "jwt-example"
spec:
  targets:
  - name: web-service
  origins:
  - jwt:
      issuer: "wsched@us.ibm.com"
      jwksUri: "https://raw.githubusercontent.com/mrsabath/jwks-test/master/jwks.json"
  principalBinding: USE_ORIGIN
