apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myubuntu
  name: myubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myubuntu
  template:
    metadata:
      annotations:
        admission.trusted.identity/inject: "true"
        tsi.secrets: |
             - tsi.secret/name: "mysecret1"
               tsi.secret/role: "tsi-role-rcni"
               tsi.secret/vault-path: "secret/tsi-rcni"
               tsi.secret/local-path: "mysecrets/myubuntu"
             - tsi.secret/name: "mysecret2.json"
               tsi.secret/role: "tsi-role-r"
               tsi.secret/vault-path: "secret/tsi-r"
               tsi.secret/local-path: "mysecrets/"
             - tsi.secret/name: "mysecret4"
               tsi.secret/role: "tsi-role-r"
               tsi.secret/vault-path: "secret/tsi-r"
               tsi.secret/local-path: "mysecrets"
             - tsi.secret/name: "password"
               tsi.secret/role: "tsi-role-r"
               tsi.secret/vault-path: "secret/tsi-r"
               tsi.secret/local-path: "mysecrets"
             - tsi.secret/name: "invalid"
               tsi.secret/role: "tsi-role-rcni"
               tsi.secret/vault-path: "secret/tsi-rcni"
               tsi.secret/local-path: "mysecrets"
             - tsi.secret/name: "non-existing"
               tsi.secret/role: "tsi-role-rcni"
               tsi.secret/vault-path: "secret/nothing"
               tsi.secret/local-path: "mysecrets"
      labels:
        app: myubuntu
      name: myubuntu
    spec:
      containers:
        - name: myubuntu
          image: ubuntu@sha256:250cc6f3f3ffc5cdaa9d8f4946ac79821aafb4d3afc93928f0de9336eba21aa4
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do cat /mydata; sleep 5; done;" ]
