apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: myubuntu
  name: myubuntu
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        admission.trusted.identity/inject: "true"
        tsi.secrets: |
             - tsi.secret/name: "mysecret1"
               tsi.secret/role: "demo"
               tsi.secret/vault-path: "secret/ti-demo-all"
               tsi.secret/local-name: "mysecrets/myubuntu-mysecret1"
             - tsi.secret/name: "mysecret2.json"
               tsi.secret/role: "demo"
               tsi.secret/vault-path: "secret/ti-demo-r"
               tsi.secret/local-name: "mysecrets/myubuntu-mysecret2"
             - tsi.secret/name: "password"
               tsi.secret/role: "demo"
               tsi.secret/vault-path: "secret/ti-demo-r"
               tsi.secret/local-name: "mysecrets/myubuntu-passwords"
             - tsi.secret/name: "invalid"
               tsi.secret/role: "demo"
               tsi.secret/vault-path: "secret/ti-demo-all"
               tsi.secret/local-name: "mysecrets/myubuntu-invalid"
             - tsi.secret/name: "non-existing"
               tsi.secret/role: "demo"
               tsi.secret/vault-path: "secret/nothing"
               tsi.secret/local-name: "mysecrets/non-existing"
      labels:
        app: myubuntu
      name: myubuntu
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: myubuntu
          image: res-kompass-kompass-docker-local.artifactory.swg-devops.com/myubuntu:latest@sha256:5b224e11f0e8daf35deb9aebc86218f1c444d2b88f89c57420a61b1b3c24584c
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do cat /mydata; sleep 5; done;" ]
