apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: myubuntu
  name: myubuntu
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        admission.trusted.identity/inject: "true"
      labels:
        app: myubuntu
      name: myubuntu
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: myubuntu
          image: res-kompass-kompass-docker-local.artifactory.swg-devops.com/myubuntu:latest
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          # args: [ "while true; do cat /mydata; sleep 5; done;" ]
          args: [ "while true; do cat /jwt-tokens/token; sleep 5; done;" ]
