apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: web-service
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: web-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-service-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-service
        version: v1
    spec:
      containers:
      - name: web-service
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: ratings
# spec:
#   gateways:
#   - ingress-gateway
#   - mesh
#   hosts:
#   - ratings.svc.a.remote
#   http:
#   - route:
#     - destination:
#         host: ratings
#         port:
#           number: 9080
# weight: 100
