apiVersion: v1
kind: Service
metadata:
  name: vtpm-service
  labels:
    app: vtpm-service
spec:
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: vtpm-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vtpm-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vtpm-service
        version: v1
    spec:
      containers:
        - name: vtpm-service
          image: trustedseriviceidentity/vtpm-server:v0.6
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 5000
            protocol: TCP
