apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ti-setter
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      name: ti-setter
  template:
    metadata:
      labels:
        name: ti-setter
    spec:
      serviceAccountName: ti-admin-sa
      # imagePullSecrets:
      # - name: regcred
      containers:
        - name: hyperkube
          image: "{{ .Values.hyperkube.repository }}:{{ .Values.hyperkube.tag }}"
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "cp -r /secrets/ /host/ti; sleep 10; kubectl delete ds ti-setter -n ti-setup;sleep 100" ]
          volumeMounts:
          - mountPath: /host/ti
            name: ti-volume
          - mountPath: /etc
            name: machine-id
            readOnly: true
          - name: jwt-secret
            mountPath: /secrets/jwt
            readOnly: true
          - name: ti-keys
            mountPath: /secrets/keys
            readOnly: true
      volumes:
      - name: ti-volume
        hostPath:
          # directory location on host
           path: /ti
           # directory might not exist
           type: DirectoryOrCreate
      - name: machine-id
        hostPath:
          # directory location on host
           path: /etc
           type: Directory
      - name: jwt-secret
        secret:
          secretName: jwt-secret
      - name: ti-keys
        secret:
          secretName: ti-keys-config
