apiVersion: v1
data:
  root-token: {{ .Values.rootToken | b64enc }}
  rootCA.crt: {{ .Values.rootCaCrt | b64enc }}
  rootCA.key: {{ .Values.rootCaKey | b64enc }}
  rootCA.srl: {{ .Values.rootCaSrl | b64enc }}
kind: Secret
metadata:
  name: ti-keys-config
  namespace: {{ .Values.namespace }}
type: Opaque
