# Default values for ti-key-release-2
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# version of ti-components
# cannot use the value from `ti-key-release-1`
# parsing problem:
#    `error converting YAML to JSON`
tiVersion: v0.20

# target docker repo
tiRepo: res-kompass-kompass-docker-local.artifactory.swg-devops.com

# Parameters below are passed to ti-key-release-1
# target namespace for the deployment
ti-key-release-1:
  namespace: trusted-identity
  # createVaultCert - if true, unique certs will be created
  # during Init Containers and inserted to Vault
  createVaultCert: false
  # if createVaultCert is set to 'true'
  # vault service endpoint is required for injecting pod specific unique key and cert.
  # see: `Automate Vault Certificates` documentation
  vaultAddress: https://169.62.157.164:32654
  # Cluster Information
  cluster:
    name: cluster-name
    region: dal01
  # Section related to JWT token creation
  jwt:
    # expireSec - Time To Live for JWT token (in seconds)
    expireSec: 30
    issuer: wsched@us.ibm.com
  # jssService - JSS Service is accessable only from within the namespace
  jssService:
    name: jss-service
    port: 8012
    # jssSerivce.type: this is the name of the image used for building JSS server
    # available options are:
    #   - jss-server - standard JSS server (deafult)
    #   - vtpm-server - vTPM v1
    #   - vtpm2-server - vTPM v2
    type: jss-server

# Not recommended for user to configure this. Hyperkube image to use when executing
# kubectl commands
hyperkube:
  repository: gcr.io/google_containers/hyperkube
  tag: v1.14.3
