# Default values for ti-key-release-2
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# version of ti-components
# cannot use the value from `ti-key-release-1`
# parsing problem:
#    `error converting YAML to JSON`
tiVersion: v0.5

# Parameters below are passed to ti-key-release-1
# target namespace for the deployment
ti-key-release-1:
  namespace: trusted-identity
  # vault endpoint:
  vaultAddress: https://169.62.157.164:32654
  # Cluster Information
  cluster:
    name: cluster-name
    region: dal01
  # Section related to JWT token creation
  jwt:
    # expireSec - Time To Live for JWT token (in seconds)
    expireSec: 30


# vtpmService - vTPM Service is accessable only from within the namespace
vtpmService:
  name: vtpm-service
  port: 8012

# Not recommended for user to configure this. Hyperkube image to use when executing
# kubectl commands
hyperkube:
  repository: quay.io/coreos/hyperkube
  tag: v1.7.6_coreos.0
